name: "Process: tidy"
on:
  pull_request:
    types: [labeled, unlabeled]
    branches:
      - main

jobs:
  setup-environment:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'dependencies' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Cache Go
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: make -j2 gomoddownload
      - name: Install Tools
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: make install-tools
      - name: go mod tidy
        run: |
          make gotidy
          git diff --exit-code || (git add **/go.mod **/go.sum && git commit -m "go mod tidy" && git push ${{ github.head_ref }})
